---
version: '2.1'

services:
  evidence-management-client-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      - "4006:4006"
    expose:
      - "4006"
    environment:
      - AUTH_PROVIDER_SERVICE_CLIENT_BASEURL=http://service-auth-provider-api:8080
      - EVIDENCE_MANAGEMENT_UPLOAD_FILE_URL=http://em-api-gateway-web:3404/documents
      - EVIDENCE_MANAGEMENT_HEALTH_URL=http://em-api-gateway-web:3404/health
      - DOCUMENT_MANAGEMENT_STORE_URL=http://document-management-store:8080
      - IDAM_API_URL=http://idam-api:8080
    links:
     - em-api-gateway-web
     - idam-api
     - service-auth-provider-api
     - document-management-store
    depends_on:
     - em-api-gateway-web
     - idam-api
     - service-auth-provider-api
     - document-management-store

  em-api-gateway-web:
     image: docker.artifactory.reform.hmcts.net/evidence/document-management-store-api-gateway-web:latest
     environment:
       - NODE_ENV=development
       - PORT=3404
       - EM_API_URL=http://document-management-store:8080
       - IDAM_BASE_URL=http://idam-api:8080
       - IDAM_S2S_URL=http://service-auth-provider-api:8080
       - IDAM_SERVICE_KEY=AAAAAAAAAAAAAAAA
       - IDAM_SERVICE_NAME=sscs
       - CORS_ORIGIN_METHODS=GET,POST,PUT,DELETE,OPTIONS
       - CORS_ORIGIN_WHITELIST=http://document-management-store:8080
       #      logging env vars
       - ROOT_APPENDER=JSON_CONSOLE
       - JSON_CONSOLE_PRETTY_PRINT=false
       - REFORM_SERVICE_TYPE=node
       - REFORM_SERVICE_NAME=em-api-gateway-web
       - REFORM_TEAM=cc
       - REFORM_ENVIRONMENT=docker
       - XFWD=true
     ports:
       - 3404:3404
     links:
      - document-management-store
      - idam-api
      - service-auth-provider-api
     depends_on:
      - document-management-store
      - idam-api
      - service-auth-provider-api

  document-management-store:
      image: docker.artifactory.reform.hmcts.net/evidence/document-management-store:latest
      command: --wait-for-database 30
      ports:
       - 3405:8080
       - 5005:5005
      expose:
        - 5005
      environment:
        - SERVER_PORT=8080
        - IDAM_SUPERUSER_EMAIL
        - IDAM_SECRET_KEY=AAAAAAAAAAAAAAAA
        - GOV_NOTIFY_API_KEY
        - SPRING_DATASOURCE_URL=jdbc:postgresql://document-management-store-database:5432/evidence
        - SPRING_DATASOURCE_USERNAME=evidence
        - SPRING_DATASOURCE_PASSWORD=evidence
        - SPRING_PROFILES_ACTIVE=dev
        - IDAM_TESTING_SUPPORT_ENABLED=true
        - LOGGING_LEVEL_UK_GOV_HMCTS_IDAM=DEBUG
        - IDAM_CLIENT_URL=http://idam-api:8080
        - PROVIDER_SERVICE_CLIENT_URL=http://service-auth-provider-api:8080
        - http_proxy=
        - https_proxy=
        - no_proxy=
  #      logging env vars
        - ROOT_APPENDER=JSON_CONSOLE
        - JSON_CONSOLE_PRETTY_PRINT=false
        - REFORM_SERVICE_TYPE=java
        - REFORM_SERVICE_NAME=document-management-store
        - REFORM_TEAM=cc
        - REFORM_ENVIRONMENT=docker
  #      healthcheck env vars
        - PACKAGES_ENVIRONMENT=docker
        - PACKAGES_PROJECT=evidence
        - PACKAGES_NAME=document-management-store
        - PACKAGES_VERSION=unknown
  #      debug mode
        - JAVA_OPTS=-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
      links:
       - document-management-store-database
       - idam-api
       - service-auth-provider-api
      depends_on:
       - document-management-store-database
       - idam-api
       - service-auth-provider-api

  document-management-store-database:
    image: docker.artifactory.reform.hmcts.net/evidence/document-management-store-database:latest

  idam-api:
    image: docker.artifactory.reform.hmcts.net/auth/idam-api:latest
    command: --wait-for-database 60
    environment:
      - IDAM_SUPERUSER_EMAIL=cmc-int-test@cmc.reform.hmcts.net
      - SPRING_DATASOURCE_URL=jdbc:postgresql://idam-database:5432/idam
      - SPRING_MAIL_HOST=smtp-server
      - IDAM_TESTING_SUPPORT_ENABLED=true
      - NOTIFY_API_KEY=${GOV_NOTIFY_API_KEY}
      - NOTIFY_CMC_ACTIVATE_USER_TEMPLATE=76aa8695-64e8-4afd-ae13-bc8385302b1f
      - IDAM_SECRET=cmc_it_test_secret_key
      - NOTIFY=false
      - NOTIFY_CMC_WELCOME_USER_TEMPLATE=fake
      - NOTIFY_DIVORCE_WELCOME_USER_TEMPLATE=fake
      - NOTIFY_SSCS_WELCOME_USER_TEMPLATE=fake
      - NOTIFY_RESET_PASSWORD_TEMPLATE=fake
      - NOTIFY_PROBATE_ACTIVATE_USER_TEMPLATE=fake
      - NOTIFY_DIVORCE_ACTIVATE_USER_TEMPLATE=fake
      - NOTIFY_SSCS_ACTIVATE_USER_TEMPLATE=fake
      - NOTIFY_CCD_ACTIVATE_USER_TEMPLATE=fake
      - http_proxy
      - https_proxy
      - no_proxy
    ports:
      - 8081:8080
    expose:
      - 8081
    links:
      - smtp-server
      - idam-database
    depends_on:
      - idam-database
      - smtp-server

  idam-database:
    image: docker.artifactory.reform.hmcts.net/auth/idam-database:latest
    ports:
      - 5430:5432

  service-auth-provider-api:
    image: docker.artifactory.reform.hmcts.net/auth/service-auth-provider-api:47e18b53aad48ae8124744041988565e07dfed50
    ports:
      - 8082:8080
    expose:
      - 8082
    environment:
      - auth.provider.service.server.jwtKey=wThK0f0/lh3FlxFcL4xUWDMI5C1J9KyQBgXV4wseh1e5J1uYJIjvTvArHxQDrYoHJ23xFxjHkOnvNbR5dXRoxA==
      - auth.provider.service.server.microserviceKeys.sscs=AAAAAAAAAAAAAAAA
      - auth.provider.service.testing-support.enabled=true

  smtp-server:
    image: mailhog/mailhog