java:
  environment:
    APPINSIGHTS_INSTRUMENTATIONKEY: "63c30ef9-a27b-4d38-8afc-4c180fb6ac33"
    AUTH_PROVIDER_SERVICE_CLIENT_KEY: ${AUTH_PROVIDER_SERVICE_CLIENT_KEY}
    AUTH_PROVIDER_SERVICE_CLIENT_MICROSERVICE: "divorce_document_generator"
    AUTH_PROVIDER_SERVICE_CLIENT_TOKENTIMETOLIVEINSECONDS: "900"
    REFORM_ENVIRONMENT: "aat"
    EVIDENCE_MANAGEMENT_HEALTH_URL: "http://dm-store-aat.service.core-compute-aat.internal/health"
    HTTP_CONNECT_REQUEST_TIMEOUT: "60000"
    DOCUMENT_MANAGEMENT_STORE_URL: "http://dm-store-aat.service.core-compute-aat.internal"
    IDAM_API_HEALTH_URI: "https://idam-api.aat.platform.hmcts.net/health"
    HTTP_CONNECT_TIMEOUT: "60000"
    APPLICATION_INSIGHTS_IKEY: "63c30ef9-a27b-4d38-8afc-4c180fb6ac33"
    HTTP_CONNECT_SOCKET_TIMEOUT: "1000"
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
    SLOT: "PRODUCTION"
    REFORM_SERVICE_NAME: "emca"
    IDAM_API_URL: "https://idam-api.aat.platform.hmcts.net"
    REFORM_TEAM: "div"

    EVIDENCE_MANAGEMENT_UPLOAD_FILE_URL: "http://dm-store-aat.service.core-compute-aat.internal/documents"